test_task:
  arm_container:
    image: haskell:9.10.1-bullseye
    cpu: 2
    memory: 8G
  test_script:
    - wget -qO - https://dl.winehq.org/wine-builds/winehq.key | apt-key add -
    - apt-add-repository https://dl.winehq.org/wine-builds/debian/
    - apt update

    # - cabal install alex

