test_task:
  arm_container:
    image: haskell:9.10.1
    cpu: 2
    memory: 8G
  test_script:
    - deb http://deb.debian.org/debian bullseye-backports main
    - sudo apt update
    - sudo apt install wine/bullseye-backports libwine/bullseye-backports fonts-wine/bullseye-backports libvkd3d1/bullseye-backports libz-mingw-w64/bullseye-backports

    # - cabal install alex

